- hosts: all
  gather_facts: no # important
  handlers:
    - name: "restart apache"
      service:
        name: apache2
        state: restarted
      become: yes
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:

    - name: "Autoremove unused dependency packages"
      apt:
        autoremove: yes
      become: yes # roda com sudo

    - name: "Update Cache"
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes # roda com sudo

    - name: "Instalar pacotes"
      apt:
        name:
          - php
          - apache2
          - libapache2-mod-php
          - php-mysql
          - php-curl
          - mysql-server
          - python3-pycurl
          - python3-mysqldb
          - unzip
        state: latest
      become: yes # roda com sudo

    - name: "Fazendo downlaod do wordpress"
      get_url:
        url: "https://br.wordpress.org/latest-pt_BR.tar.gz"
        dest: "/tmp/wordpress.tar.gz"
    
    - name: "Fazendo descompactação dos arquivos do WP"
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www"
        remote_src: yes
      become: yes

    - name: "Copia arquivo WP"
      copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes

    - name: "Configura o wp-config com as senhas"
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: 'nome_do_banco_de_dados_aqui', value: 'banco_wordpress' }
        - { regex: 'nome_de_usuario_aqui', value: 'root' }
        - { regex: 'senha_aqui', value: 'root' }
      become: yes

    - name: "Trocando pasta do render do apache para o wordpress"
      copy:
        src: "apache/000-default.conf"
        dest: "/etc/apache2/sites-available/000-default.conf"
      become: yes
      notify:
        - "restart apache"
  
    - name: "Levanta serviço do mysql"
      become: yes
      service:
        name: mysql
        state: started

    - name: "Criando senha root mysql"
      become: yes
      mysql_user:
        name: root
        host: localhost
        password: root
        priv: "*.*:ALL,GRANT"
  
    - name: "Cria o banco de dados MySQL"
      mysql_db:
        name: banco_wordpress
        login_user: root
        login_password: root
        state: present

#    - name: "Copiar base do banco de dados"
#      copy:
#        src: "mysql_dump/wp_roan.mysql"
#        dest: "/tmp/wp_roan.mysql"
#      become: yes

#    - name: "Inicia importe do banco de dados"
#      mysql_db:
#        name: banco_wordpress
#        state: import
#        src: /tmp/wp_roan.mysql"
#        #target: /tmp/wp_roan.mysql"
#        #login_host: 127.0.0.1
#        login_user: root
#        login_password: root

    - name: "Copiando novo tema WP"
      copy:
        src: "thema/generatepress.3.0.3.zip"
        dest: "/tmp/generatepress.3.0.3.zip"
      become: yes

    - name: "Descompactar na pasta do thema"
      unarchive:
        src: "/tmp/generatepress.3.0.3.zip"
        dest: "/var/www/wordpress/wp-content/themes/"
        remote_src: yes
      become: yes

    - name: "Copiando novo plugin new relic WP"
      copy:
        src: "plugins/rt-newrelic-browser.1.0.5.zip"
        dest: "/tmp/rt-newrelic-browser.1.0.5.zip"
      become: yes

    - name: "Descompactar na pasta do plugins o newrelic"
      unarchive:
        src: "/tmp/rt-newrelic-browser.1.0.5.zip"
        dest: "/var/www/wordpress/wp-content/plugins/"
        remote_src: yes
      become: yes

    # - name: "Instalando newrelic server metrics"
    #   shell: "curl -Ls https://raw.githubusercontent.com/newrelic/newrelic-cli/master/scripts/install.sh | bash && sudo NEW_RELIC_API_KEY=NRAK-MVTZUUU8ML7BTBXJVFEPJF46TBQ NEW_RELIC_ACCOUNT_ID=1134562 /usr/local/bin/newrelic install"
